{"uuid": "876df924-7e0e-4c60-b216-0875b804dca4", "children": ["dba265fe-8003-426c-b5e4-7a0c74b152a8"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/imgd/ctpriv-scripts/altice/wlan-testing/tests/e2e/basic/conftest.py\", line 80, in setup_profiles\n  File \"/home/imgd/Projects/ctpriv-scripts/altice/wlan-testing/tests/fixtures_4x.py\", line 111, in setup_profiles\n    instantiate_profile_obj.check_and_set_ssid_sec(\"2G\", profile_data[\"ssid\"][mode][0][\n  File \"/home/imgd/Projects/ctpriv-scripts/altice/wlan-testing/tests/../libs/controller/controller_4x/controller.py\", line 670, in check_and_set_ssid_sec\n    self.get_all_ssid_detail(radio=radio)\n  File \"/home/imgd/Projects/ctpriv-scripts/altice/wlan-testing/tests/../libs/controller/controller_4x/controller.py\", line 716, in get_all_ssid_detail\n    ssid_details = self.run_generic_cli_command(cmd)\n  File \"/home/imgd/Projects/ctpriv-scripts/altice/wlan-testing/tests/../libs/controller/controller_4x/controller.py\", line 180, in run_generic_cli_command\n    output = os.popen(cmd).read()\n"}, "start": 1696922820217, "stop": 1696929109171}], "start": 1696922820217, "stop": 1696929109373}